### ISSUE TITLE
上線前準備

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/check-in-frontend#6]
- [x] helmet information
- [x] 埋ＧＡ
- [x] icon of browser

**Comment by mark86092** [comment]
- [ ] google search console

**Comment by mark86092** [comment]
這個的狀態是什麼？

**Comment by barry800414** [comment]
google search console 我不確定你要我設定什麼？

**Comment by mark86092** [comment]
我昨天看的時候還缺 icon of browser，你是剛剛打勾的嗎？

**Comment by barry800414** [comment]
對！ 剛剛打勾的，已經補上了

我想問 google search console 那邊要做什麼設定嗎？

**Comment by mark86092** [comment]
到這裡：https://www.google.com/webmasters/tools/home?hl=zh-TW

加上前端的 https 網址資源
